# Generated by Django 2.1.5 on 2019-03-06 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hash',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
