# Generated by Django 2.1.5 on 2019-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20190307_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
